const movies = [
  {
    id: 1,
    isWatchlist: true,
    isFavorite: false,
    meta: {
      vote_average: 8.7,
      popularity: 41.134,
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      release_date: "1972-03-14",
      adult: false,
      backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
      title: "The Godfather",
      genre_ids: [18, 80],
      vote_count: 13301,
      original_language: "en",
      original_title: "The Godfather",
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      id: 238,
      video: false,
    },
  },
  {
    id: 2,
    isWatchlist: true,
    isFavorite: true,
    meta: {
      vote_average: 8.3,
      popularity: 38.068,
      vote_count: 14114,
      release_date: "1985-07-03",
      adult: false,
      backdrop_path: "/fq3wyOs1RHyz2yfzsb4sck7aWRG.jpg",
      title: "Back to the Future",
      genre_ids: [12, 35, 878, 10751],
      poster_path: "/xlBivetfrtF84Yx0zISShnNtHYe.jpg",
      original_language: "en",
      original_title: "Back to the Future",
      id: 105,
      overview:
        "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
      video: false,
    },
  },
  {
    id: 3,
    isWatchlist: false,
    isFavorite: false,
    meta: {
      vote_average: 8.3,
      popularity: 36.631,
      vote_count: 10141,
      release_date: "1994-09-14",
      adult: false,
      backdrop_path: "/jRJrQ72VLyEnVsvwfep8Xjlvu8c.jpg",
      title: "Léon: The Professional",
      genre_ids: [80, 18, 28],
      poster_path: "/91bUbxcOvTinqrPLrnGHlWYVy9J.jpg",
      original_language: "en",
      original_title: "Léon: The Professional",
      id: 101,
      overview:
        "Léon, the top hit man in New York, has earned a rep as an effective \"cleaner\". But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda's thoughts turn to revenge, and she considers following in Léon's footsteps.",
      video: false,
    },
  },
  {
    id: 4,
    isWatchlist: true,
    isFavorite: true,
    meta: {
      video: false,
      vote_average: 8.4,
      popularity: 40.64,
      overview:
        'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
      release_date: "1999-10-15",
      adult: false,
      backdrop_path: "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
      id: 550,
      genre_ids: [18],
      title: "Fight Club",
      original_language: "en",
      original_title: "Fight Club",
      poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
      vote_count: 20477,
    },
  },
  {
    id: 5,
    isWatchlist: true,
    isFavorite: false,
    meta: {
      original_title: "Forrest Gump",
      poster_path: "/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg",
      video: false,
      vote_average: 8.5,
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      release_date: "1994-07-06",
      title: "Forrest Gump",
      popularity: 40.68,
      vote_count: 19302,
      id: 13,
      adult: false,
      genre_ids: [35, 18, 10749],
      backdrop_path: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg",
      original_language: "en",
    },
  },
  {
    id: 6,
    isWatchlist: true,
    isFavorite: true,
    meta: {
      video: false,
      id: 603,
      popularity: 51.984,
      overview:
        "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      release_date: "1999-03-30",
      title: "The Matrix",
      backdrop_path: "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
      vote_average: 8.1,
      genre_ids: [28, 878],
      vote_count: 18094,
      original_language: "en",
      original_title: "The Matrix",
      poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      adult: false,
    },
  },
];

export default movies;
